# Generated by Django 5.0.6 on 2025-02-24 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('number_of_lessons', models.IntegerField(default=0)),
                ('chapter_plan', models.FileField(blank=True, null=True, upload_to='chapter_plan/')),
                ('status', models.BooleanField(default=True)),
                ('is_admin_aproved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('assignment', models.FileField(blank=True, null=True, upload_to='assignment/')),
                ('lsat_date_of_submission', models.DateField(blank=True, null=True)),
                ('live_class_date', models.DateTimeField(blank=True, null=True)),
                ('live_class_link', models.URLField(blank=True, null=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='resource_file/')),
                ('lesson_video', models.FileField(blank=True, null=True, upload_to='lesson_video/')),
                ('iframe_data', models.TextField(blank=True, null=True)),
                ('lesson_note', models.FileField(blank=True, null=True, upload_to='lesson_note/')),
                ('status', models.BooleanField(default=True)),
                ('is_admin_aproved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('exam_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('exam_link', models.URLField(blank=True, null=True)),
                ('is_mcq', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('is_admin_aproved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.chapters')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FileField(upload_to='assignment_submission/')),
                ('marks', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correct_option', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.exams')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.exams')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_description', models.TextField(blank=True, null=True)),
                ('subject_image', models.ImageField(blank=True, null=True, upload_to='subjects/')),
                ('course_enrole_fee', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_admin_aproved', models.BooleanField(default=False)),
                ('senester_rank', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.subjects'),
        ),
        migrations.CreateModel(
            name='CourseEnrollApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('is_admin_aproved', models.BooleanField(default=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.subjects'),
        ),
    ]
